name: Create a new Repository
description: Template to provice input for repo creation
title: "GitHub setting up IssueOps"
labels: ["newRepo"]
body:
  - type: "input"
    attributes:
      label: ">>repo-name<<"
      description: "New Repo name"
      placeholder: "Add name"
    validations:
      required: true
